# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"strip_text": "01-preprocessing.ipynb",
         "replace_whitespace": "01-preprocessing.ipynb",
         "whitespace_pattern": "01-preprocessing.ipynb",
         "replace_URLs": "01-preprocessing.ipynb",
         "url_pattern": "01-preprocessing.ipynb",
         "replace_user": "01-preprocessing.ipynb",
         "user_pattern": "01-preprocessing.ipynb",
         "is_wrong_selection": "01-preprocessing.ipynb",
         "get_answer_start": "01-squad-utils.ipynb",
         "generate_qas_dict": "01-squad-utils.ipynb",
         "create_squad_from_df": "01-squad-utils.ipynb",
         "save_dict_as_json": "01-squad-utils.ipynb",
         "read_json_as_dict": "01-squad-utils.ipynb",
         "init_roberta_tokenizer": "02-tokenizers.ipynb",
         "get_start_end_idxs": "03-datasets.ipynb",
         "get_start_end_tok_idxs": "03-datasets.ipynb",
         "QAInputGenerator": "03-datasets.ipynb",
         "TSEDataAugmentor": "03-datasets.ipynb",
         "do_tfms": "04-models.ipynb",
         "TSEDataset": "03-datasets.ipynb",
         "get_roberta_model": "04-models.ipynb",
         "QAHead": "04-models.ipynb",
         "TSEModel": "04-models.ipynb",
         "noop_layer": "04-models.ipynb",
         "CELoss": "04-models.ipynb",
         "LSLoss": "04-models.ipynb",
         "jaccard": "04-models.ipynb",
         "get_best_start_end_idxs": "04-models.ipynb",
         "JaccardScore": "04-models.ipynb",
         "model_split_func": "04-models.ipynb"}

modules = ["preprocessing.py",
           "squad_utils.py",
           "tokenizers.py",
           "datasets.py",
           "models.py"]

doc_url = "https://fastai.github.io/tse/"

git_url = "https://github.com/fastai/tse/tree/master/"

def custom_doc_links(name): return None
