# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_answer_start": "01-squad-utils.ipynb",
         "generate_qas_dict": "01-squad-utils.ipynb",
         "create_squad_from_df": "01-squad-utils.ipynb",
         "save_dict_as_json": "01-squad-utils.ipynb",
         "read_json_as_dict": "01-squad-utils.ipynb",
         "squad_processor": "02-tokenizers.ipynb",
         "get_squad_dataset": "02-tokenizers.ipynb",
         "MAX_SEQ_LEN": "02-tokenizers.ipynb",
         "MAX_QUERY_LEN": "02-tokenizers.ipynb",
         "DOC_STRIDE": "02-tokenizers.ipynb",
         "find_best_start_end_idxs": "02-tokenizers.ipynb",
         "answer_from_orig_context": "02-tokenizers.ipynb",
         "SQUAD_DATA_PATH": "03-datasets.ipynb",
         "PRETRAINED_TOK_PATH": "03-datasets.ipynb",
         "TSEDataAugmentor": "03-datasets.ipynb",
         "SQUAD_Dataset": "03-datasets.ipynb",
         "get_fold_ds": "03-datasets.ipynb",
         "predict_answer_text": "03-datasets.ipynb"}

modules = ["squad_utils.py",
           "tokenizers.py",
           "datasets.py"]

doc_url = "https://fastai.github.io/tse/"

git_url = "https://github.com/fastai/tse/tree/master/"

def custom_doc_links(name): return None
